version: "3.8"

networks:
  inception:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/rsiqueir/data/mariadb_vol
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/rsiqueir/data/wordpress_vol
      o: bind

services:
  mariadb:
    init: true
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    env_file: [.env]
    expose:
      - "3306"
    restart: always

  wordpress:
    init: true
    container_name: wordpress
    image: wordpress
    depends_on:        
      - mariadb
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_vol:/var/www/wordpress
    networks:
      - inception
    env_file: .env
    expose: 
      - "9000"
    restart: always
  
  nginx:
    init: true
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_vol:/var/www/wordpress
    networks:
      - inception
    env_file: .env
    ports:
      - "443:443"     
    restart: always
